// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CattleyaToursContext))]
    [Migration("20230818151334_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("backend.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaActividadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaActividadId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("backend.Models.ArchivoSitioTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SitioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SitioId");

                    b.ToTable("ArchivosSitioTuristico");
                });

            modelBuilder.Entity("backend.Models.CategoriaActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriasActividad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Participa en actividades como creación de artesanías, taller de fotografía entre otras.",
                            Icono = "fas fa-pencil-ruler",
                            Nombre = "Talleres"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Prueba las delicias típicas de nuestra tierra, en sitios únicos y vive una experiencia inolvidable.",
                            Icono = "fas fa-utensils",
                            Nombre = "Gastronomía"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Recorre los parques y reservas naturales más famosas de nuestro país en compañía de expertos.",
                            Icono = "fas fa-map-marked-alt",
                            Nombre = "Visitas guiadas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Visita sitios únicos en el mundo como cascadas naturales, volcanes y nevados.",
                            Icono = "fas fa-hiking",
                            Nombre = "Maravillas naturales"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Experimenta el vértigo y la adrenalina practicando deportes extremos como rapel, parapente, paracaidismo, canotaje, ciclomontañismo, entre otros.",
                            Icono = "fas fa-biking",
                            Nombre = "Deportes extremos"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Disfruta de atracciones mecánicas en los parques de diversiones más famosos del país.",
                            Icono = "fas fa-rocket",
                            Nombre = "Atracciones mecánicas"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Sal de la ciudad y pasa un fin de semana alejado del estrés acampando en sitios extraordinarios disfrutando de la naturaleza en su máximo esplendor.",
                            Icono = "fas fa-campground",
                            Nombre = "Glamping"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Vive una noche inolvidable junto a tus amigos disfrutando la sorprendente vida nocturna que tenemos para ofrecerte.",
                            Icono = "fas fa-glass-cheers",
                            Nombre = "Rumba"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Disfruta la experiencia de alimentar y convivir con animales de la región, acompañado por los mejores guías.",
                            Icono = "fas fa-paw",
                            Nombre = "Experiencias con animales"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Realiza actividades originales y divertidas únicas de cada sitio.",
                            Icono = "fas fa-ellipsis-h",
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("backend.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2023, 8, 18, 10, 13, 34, 815, DateTimeKind.Local).AddTicks(3216));

                    b.Property<int>("PublicacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("Username");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("backend.Models.Interes", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2023, 8, 18, 10, 13, 34, 815, DateTimeKind.Local).AddTicks(5851));

                    b.HasKey("Username", "PublicacionId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Intereses");
                });

            modelBuilder.Entity("backend.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropietarioUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SitioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioUsername");

                    b.HasIndex("SitioId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoReserva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2023, 8, 18, 10, 13, 34, 815, DateTimeKind.Local).AddTicks(8396));

                    b.HasKey("Username", "PublicacionId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("backend.Models.SitioTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropietarioUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioUsername");

                    b.ToTable("SitiosTuristicos");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Actividad", b =>
                {
                    b.HasOne("backend.Models.CategoriaActividad", "CategoriaActividad")
                        .WithMany()
                        .HasForeignKey("CategoriaActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Publicacion", "Publicacion")
                        .WithMany("Actividades")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaActividad");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("backend.Models.ArchivoSitioTuristico", b =>
                {
                    b.HasOne("backend.Models.SitioTuristico", "Sitio")
                        .WithMany("Imagenes")
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("backend.Models.Comentario", b =>
                {
                    b.HasOne("backend.Models.Publicacion", "Publicacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Interes", b =>
                {
                    b.HasOne("backend.Models.Publicacion", "Publicacion")
                        .WithMany("Intereses")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Intereses")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Publicacion", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.SitioTuristico", "Sitio")
                        .WithMany()
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.HasOne("backend.Models.Publicacion", "Publicacion")
                        .WithMany("Reservas")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.SitioTuristico", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("PropietarioUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("backend.Models.Publicacion", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Comentarios");

                    b.Navigation("Intereses");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("backend.Models.SitioTuristico", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Intereses");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
